export const userConstants = {
    // Auth
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    LOGOUT: 'USERS_LOGOUT',

    // Order History Constants
    ALL_ORDER_REQUEST: 'ALL_ORDER_REQUEST',
    ALL_ORDER_SUCCESS: 'ALL_ORDER_SUCCESS',
    ALL_ORDER_FAILURE: 'ALL_ORDER_FAILURE',
    SINGLE_ORDER_REQUEST: 'SINGLE_ORDER_REQUEST',
    SINGLE_ORDER_SUCCESS: 'SINGLE_ORDER_SUCCESS',
    SINGLE_ORDER_FAILURE: 'SINGLE_ORDER_FAILURE',
    /**
     * API Header : Will be changed when deployed
     */
    API_HEADER: 'http://127.0.0.1:8000',

    /**
     * Inventory Management Constants
     */

    // Upload Inventory
    UPLOAD_INVENTORY_REQUEST: 'UPLOAD_INVENTORY_REQUEST',
    UPLOAD_INVENTORY_SUCCESS: 'UPLOAD_INVENTORY_SUCCESS',
    UPLOAD_INVENTORY_FAILURE: 'UPLOAD_INVENTORY_FAILURE',
    
    // Get Inventory
    GET_INVENTORY_REQUEST: 'GET_INVENTORY_REQUEST',
    GET_INVENTORY_SUCCESS: 'GET_INVENTORY_SUCCESS',
    GET_INVENTORY_FAILURE: 'GET_INVENTORY_FAILURE',

    // Mark Meds Available
    MARK_AVAILABLE_SUCCESS: 'MARK_AVAILABLE_SUCCESS',
    MARK_AVAILABLE_FAILURE: 'MARK_AVAILABLE_FAILURE',

    // Mark Meds Unavailable
    MARK_UNAVAILABLE_SUCCESS: 'MARK_UNAVAILABLE_SUCCESS',
    MARK_UNAVAILABLE_FAILURE: 'MARK_UNAVAILABLE_FAILURE',
};