export const userConstants = {
    // Auth
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    LOGOUT: 'USERS_LOGOUT',

    // Order History Constants
    ALL_ORDER_REQUEST: 'ALL_ORDER_REQUEST',
    ALL_ORDER_SUCCESS: 'ALL_ORDER_SUCCESS',
    ALL_ORDER_FAILURE: 'ALL_ORDER_FAILURE',
    SINGLE_ORDER_REQUEST: 'SINGLE_ORDER_REQUEST',
    SINGLE_ORDER_SUCCESS: 'SINGLE_ORDER_SUCCESS',
    SINGLE_ORDER_FAILURE: 'SINGLE_ORDER_FAILURE',
    /**
     * API Header : Will be changed when deployed
     */
    API_HEADER: 'http://52.16.159.60',
    // API_HEADER: 'http://localhost:8000',    

    /*** Ecom Process */
    
    // Prescription upload
    PRESCRIPTION_UPLOAD_REQUEST: 'PRESCRIPTION_UPLOAD_REQUEST',
    PRESCRIPTION_UPLOAD_FAILURE: 'PRESCRIPTION_UPLOAD_FAILURE',
    PRESCRIPTION_UPLOAD_SUCCESS: 'PRESCRIPTION_UPLOAD_SUCCESS',
    
    // Cart functions
    ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    // REMOVE_FROM_CART_REQUEST: 'REMOVE_FROM_CART_REQUEST',
    REMOVE_FROM_CART_FAILURE: 'REMOVE_FROM_CART_FAILURE',
    REMOVE_FROM_CART_SUCCESS: 'REMOVE_FROM_CART_SUCCESS',

    // Pharmacy List

    // Get cart details, shipping address, billing address
    GET_CART_DETAILS_REQUEST: 'GET_CART_DETAILS_REQUEST',
    GET_CART_DETAILS_SUCCESS: 'GET_CART_DETAILS_SUCCESS',
    GET_CART_DETAILS_FAILURE: 'GET_CART_DETAILS_FAILURE',
    
    // Checkout (pharmacy selected and details confirmed)
    CHECKOUT_REQUEST: 'CHECKOUT_REQUEST',
    CHECKOUT_SUCCESS: 'CHECKOUT_SUCCESS',
    CHECKOUT_FAILURE: 'CHECKOUT_FAILURE',

    // Payment
};
